### ISSUE TITLE
Make service compatible with WebdriverIO v5

### ISSUE THREAD

**Issue by christian-bromann** [wenjunche/wdio-openfin-service#1]
Hola 👋 

WebdriverIO released v5 around Christmas, see also [this blogpost](https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html). To make this service usable with the new version there are some small adjustments necessary. There are some minor changes that need to be made. You can find a general overview [here](https://webdriver.io/docs/customreporter.html). Most important ones to point out are:

- set `"@wdio/cli": "^5.0.0"` as peerDependency
- if you have launcher and a service you should create an index.js and expose both classes as follows:
  ```js  
  import Launcher from './launcher'
  import Service from './service'

  export default Service
  export const launcher = Launcher
  ```

Feel free to drop by the [`webdriverio`](https://gitter.im/webdriverio/webdriverio) support channel in case you need support.

Thanks so much for contributing to the WebdriverIO community. We really appreciate it 🙏 !

**Comment by wenjunche** [comment]
Hello

I just pushed some changes to be compatible with wdio v5.

Thank you for letting us know.

**Comment by christian-bromann** [comment]
Thank you! Feel free to add the service to the [list of supported services](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/config.js#L23-L38).
